### ISSUE TITLE
Logo size

### ISSUE THREAD

**Issue by ges-na** [pitt-crc/biostar-central#8]
Is there a constraint to the size of the logo (e.g. based on the "Community," "Planet," etc. buttons to the right of the logo) or could it be made larger? I'd suggest at least 100px height if possible--but I defer if there are web standards for sizing!

**Comment by fangpingmu** [comment]
There is a constraint. I don't suggest changing its height. How about do I change its width?

**Comment by ges-na** [comment]
I don't think changing the width would make sense if we can't change the height too. I don't mind closing this given the height constraint.
